// Ported from min2phase by Chen Shuang (https://github.com/cs0x7f/min2phase).
//
// Two-dimensional Java tables are flattened: `table[row * columns + column]`.

let nSlice = 495
let nTwist = 2187
let nTwistSym = 324
let nFlip = 2048
let nFlipSym = 336
let nPerm = 40320
let nPermSym = 2768
let nMPerm = 24
let nComb = 140
let p2ParityMove = 0xA5
let symE2CMagic = 0x00DD_DD00

/// Maps an edge-permutation sym coordinate to the matching corner-permutation sym coordinate.
func eSym2CSym(_ idx: Int) -> Int {
    idx ^ ((symE2CMagic >> ((idx & 0xf) << 1)) & 3)
}

@inline(__always)
func getPruning(_ table: [UInt32], _ index: Int) -> Int {
    Int((table[index >> 3] >> UInt32((index & 7) << 2)) & 0xf)
}

@inline(__always)
func setPruning(_ table: inout [UInt32], _ index: Int, _ value: Int) {
    table[index >> 3] ^= UInt32(value) << UInt32((index & 7) << 2)
}

/// The 16 symmetries preserving the UD axis (generated by S_F2, S_U4 and S_LR2).
struct Symmetries: Sendable {
    let cubeSym: [CubieCube]
    /// [16 * 16]: symMult[i * 16 + j] = k where S_i * S_j = S_k.
    let symMult: [Int]
    let symMultInv: [Int]

    init() {
        var c = CubieCube()
        var d = CubieCube()
        let f2 = CubieCube(cperm: 28783, twist: 0, eperm: 259_268_407, flip: 0)
        let u4 = CubieCube(cperm: 15138, twist: 0, eperm: 119_765_538, flip: 7)
        var lr2 = CubieCube(cperm: 5167, twist: 0, eperm: 83_473_207, flip: 0)
        for i in 0..<8 {
            lr2.ca[i] |= 3 << 3
        }

        var cubeSym: [CubieCube] = []
        for i in 0..<16 {
            cubeSym.append(c)
            CubieCube.cornMultFull(c, u4, &d)
            CubieCube.edgeMult(c, u4, &d)
            swap(&c, &d)
            if i % 4 == 3 {
                CubieCube.cornMultFull(c, lr2, &d)
                CubieCube.edgeMult(c, lr2, &d)
                swap(&c, &d)
            }
            if i % 8 == 7 {
                CubieCube.cornMultFull(c, f2, &d)
                CubieCube.edgeMult(c, f2, &d)
                swap(&c, &d)
            }
        }

        var symMult = [Int](repeating: 0, count: 256)
        var symMultInv = [Int](repeating: 0, count: 256)
        for i in 0..<16 {
            for j in 0..<16 {
                CubieCube.cornMultFull(cubeSym[i], cubeSym[j], &c)
                let k = cubeSym.firstIndex { $0.ca == c.ca }!
                symMult[i * 16 + j] = k
                symMultInv[k * 16 + j] = i
            }
        }
        self.cubeSym = cubeSym
        self.symMult = symMult
        self.symMultInv = symMultInv
    }

    /// b = S_idx^-1 * a * S_idx, corners only.
    func cornConjugate(_ a: CubieCube, _ idx: Int, _ b: inout CubieCube) {
        CubieCube.cornConjugate(a, s: cubeSym[idx], sinv: cubeSym[symMultInv[idx]], &b)
    }

    /// b = S_idx^-1 * a * S_idx, edges only.
    func edgeConjugate(_ a: CubieCube, _ idx: Int, _ b: inout CubieCube) {
        CubieCube.edgeConjugate(a, s: cubeSym[idx], sinv: cubeSym[symMultInv[idx]], &b)
    }

    /// Bitmask of the 48 symmetries (16 x URF conjugation x inversion) that leave `cube` unchanged.
    func selfSymmetry(_ cube: CubieCube) -> UInt64 {
        var c = cube
        var d = CubieCube()
        var sym: UInt64 = 0
        for urfInv in 0..<6 {
            for i in 0..<16 {
                cornConjugate(c, symMultInv[i], &d)
                if d.ca == cube.ca {
                    edgeConjugate(c, symMultInv[i], &d)
                    if d.ea == cube.ea {
                        sym |= 1 << UInt64(min((urfInv << 4) | i, 48))
                    }
                }
            }
            c.urfConjugate()
            if urfInv % 3 == 2 {
                c.invert()
            }
        }
        return sym
    }
}

/// Move, symmetry and pruning tables. Building them takes a moment, so share one instance.
final class Tables: Sendable {
    static let shared = Tables()

    let sym: Symmetries
    let symMult: [Int]
    let symMultInv: [Int]
    /// [16 * 18]
    let symMove: [Int]
    /// [16 * 18], phase 2 move indices.
    let symMoveUD: [Int]
    /// [18 * 8]
    let sym8Move: [Int]
    let moveCubeSym: [UInt64]
    let firstMoveSym: [Int]

    // Sym-coordinate <-> raw-coordinate maps.
    let flipR2S: [Int]
    let flipS2RF: [Int]
    let twistR2S: [Int]
    let ePermR2S: [Int]
    let perm2CombP: [Int]
    let permInvEdgeSym: [Int]
    let mPermInv: [Int]

    // Phase 1 move/conjugation tables.
    let udSliceMove: [Int]  // [495 * 18]
    let twistMove: [Int]  // [324 * 18]
    let flipMove: [Int]  // [336 * 18]
    let udSliceConj: [Int]  // [495 * 8]

    // Phase 2 move/conjugation tables.
    let cPermMove: [Int]  // [2768 * 10]
    let ePermMove: [Int]  // [2768 * 10]
    let mPermMove: [Int]  // [24 * 10]
    let mPermConj: [Int]  // [24 * 16]
    let cCombPConj: [Int]  // [140 * 16]

    // Pruning tables, 8 four-bit entries per word.
    let udSliceTwistPrun: [UInt32]
    let udSliceFlipPrun: [UInt32]
    let twistFlipPrun: [UInt32]
    let mcPermPrun: [UInt32]
    let ePermCCombPPrun: [UInt32]

    init() {
        let sym = Symmetries()
        let mc = CubieCube.moveCube
        var c = CubieCube()

        // Symmetry-move tables.
        var symMove = [Int](repeating: 0, count: 16 * 18)
        var symMoveUD = [Int](repeating: 0, count: 16 * 18)
        var sym8Move = [Int](repeating: 0, count: 8 * 18)
        for j in 0..<18 {
            for s in 0..<16 {
                sym.cornConjugate(mc[j], sym.symMultInv[s], &c)
                let m = mc.firstIndex { $0.ca == c.ca }!
                symMove[s * 18 + j] = m
                symMoveUD[s * 18 + Util.std2ud[j]] = Util.std2ud[m]
                if s % 2 == 0 {
                    sym8Move[(j << 3) | (s >> 1)] = m
                }
            }
        }

        var moveCubeSym = [UInt64](repeating: 0, count: 18)
        var firstMoveSym = [Int](repeating: 0, count: 48)
        for i in 0..<18 {
            moveCubeSym[i] = sym.selfSymmetry(mc[i])
            var j = i
            for s in 0..<48 {
                if symMove[(s % 16) * 18 + j] < i {
                    firstMoveSym[s] |= 1 << i
                }
                if s % 16 == 15 {
                    j = CubieCube.urfMove[2][j]
                }
            }
        }

        // Sym coordinates.
        let perm = Self.initSym2Raw(nRaw: nPerm, nSym: nPermSym, coord: .perm, sym: sym)
        let ePermR2S = perm.raw2Sym
        let ePermS2R = perm.sym2Raw
        var perm2CombP = [Int](repeating: 0, count: nPermSym)
        var permInvEdgeSym = [Int](repeating: 0, count: nPermSym)
        c = CubieCube()
        for i in 0..<nPermSym {
            c.setEPerm(ePermS2R[i])
            perm2CombP[i] = Util.getComb(c.ea, mask: 0, isEdge: true) + Util.getNParity(ePermS2R[i], 8) * 70
            c.invert()
            permInvEdgeSym[i] = ePermR2S[c.eperm]
        }
        var mPermInv = [Int](repeating: 0, count: nMPerm)
        for i in 0..<nMPerm {
            c.setMPerm(i)
            c.invert()
            mPermInv[i] = c.mperm
        }

        var d = CubieCube()

        var cPermMove = [Int](repeating: 0, count: nPermSym * 10)
        c = CubieCube()
        for i in 0..<nPermSym {
            c.setCPerm(ePermS2R[i])
            for j in 0..<10 {
                CubieCube.cornMult(c, mc[Util.ud2std[j]], &d)
                cPermMove[i * 10 + j] = eSym2CSym(ePermR2S[d.cperm])
            }
        }

        var ePermMove = [Int](repeating: 0, count: nPermSym * 10)
        c = CubieCube()
        for i in 0..<nPermSym {
            c.setEPerm(ePermS2R[i])
            for j in 0..<10 {
                CubieCube.edgeMult(c, mc[Util.ud2std[j]], &d)
                ePermMove[i * 10 + j] = ePermR2S[d.eperm]
            }
        }

        var mPermMove = [Int](repeating: 0, count: nMPerm * 10)
        var mPermConj = [Int](repeating: 0, count: nMPerm * 16)
        c = CubieCube()
        for i in 0..<nMPerm {
            c.setMPerm(i)
            for j in 0..<10 {
                CubieCube.edgeMult(c, mc[Util.ud2std[j]], &d)
                mPermMove[i * 10 + j] = d.mperm
            }
            for j in 0..<16 {
                sym.edgeConjugate(c, sym.symMultInv[j], &d)
                mPermConj[i * 16 + j] = d.mperm
            }
        }

        var cCombPMove = [Int](repeating: 0, count: nComb * 10)
        var cCombPConj = [Int](repeating: 0, count: nComb * 16)
        c = CubieCube()
        for i in 0..<nComb {
            c.setCComb(i % 70)
            for j in 0..<10 {
                CubieCube.cornMult(c, mc[Util.ud2std[j]], &d)
                cCombPMove[i * 10 + j] = d.ccomb + 70 * (((p2ParityMove >> j) & 1) ^ (i / 70))
            }
            for j in 0..<16 {
                sym.cornConjugate(c, sym.symMultInv[j], &d)
                cCombPConj[i * 16 + j] = d.ccomb + 70 * (i / 70)
            }
        }

        let flip = Self.initSym2Raw(nRaw: nFlip, nSym: nFlipSym, coord: .flip, sym: sym)
        let twist = Self.initSym2Raw(nRaw: nTwist, nSym: nTwistSym, coord: .twist, sym: sym)

        var flipMove = [Int](repeating: 0, count: nFlipSym * 18)
        c = CubieCube()
        for i in 0..<nFlipSym {
            c.setFlip(flip.sym2Raw[i])
            for j in 0..<18 {
                CubieCube.edgeMult(c, mc[j], &d)
                flipMove[i * 18 + j] = flip.raw2Sym[d.flip]
            }
        }

        var twistMove = [Int](repeating: 0, count: nTwistSym * 18)
        c = CubieCube()
        for i in 0..<nTwistSym {
            c.setTwist(twist.sym2Raw[i])
            for j in 0..<18 {
                CubieCube.cornMult(c, mc[j], &d)
                twistMove[i * 18 + j] = twist.raw2Sym[d.twist]
            }
        }

        var udSliceMove = [Int](repeating: 0, count: nSlice * 18)
        var udSliceConj = [Int](repeating: 0, count: nSlice * 8)
        c = CubieCube()
        for i in 0..<nSlice {
            c.setUDSlice(i)
            for j in stride(from: 0, to: 18, by: 3) {
                CubieCube.edgeMult(c, mc[j], &d)
                udSliceMove[i * 18 + j] = d.udSlice
            }
            for j in stride(from: 0, to: 16, by: 2) {
                sym.edgeConjugate(c, sym.symMultInv[j], &d)
                udSliceConj[i * 8 + (j >> 1)] = d.udSlice
            }
        }
        for i in 0..<nSlice {
            for j in stride(from: 0, to: 18, by: 3) {
                var udslice = udSliceMove[i * 18 + j]
                for k in 1..<3 {
                    udslice = udSliceMove[udslice * 18 + j]
                    udSliceMove[i * 18 + j + k] = udslice
                }
            }
        }

        // Pruning tables.
        let flipTables = FlipTables(flipR2S: flip.raw2Sym, flipS2RF: flip.sym2RawFull, flipMove: flipMove, sym8Move: sym8Move)
        mcPermPrun = Self.initRawSymPrun(
            raw: (mPermMove, mPermConj, 16), symMove: cPermMove, symState: perm.symState, flag: 0x8ea34)
        ePermCCombPPrun = Self.initRawSymPrun(
            raw: (cCombPMove, cCombPConj, 16), symMove: ePermMove, symState: perm.symState, flag: 0x7d824)
        udSliceTwistPrun = Self.initRawSymPrun(
            raw: (udSliceMove, udSliceConj, 8), symMove: twistMove, symState: twist.symState, flag: 0x69603)
        udSliceFlipPrun = Self.initRawSymPrun(
            raw: (udSliceMove, udSliceConj, 8), symMove: flipMove, symState: flip.symState, flag: 0x69603)
        twistFlipPrun = Self.initRawSymPrun(
            raw: nil, flipTables: flipTables, symMove: twistMove, symState: twist.symState, flag: 0x19603)

        self.sym = sym
        self.symMult = sym.symMult
        self.symMultInv = sym.symMultInv
        self.symMove = symMove
        self.symMoveUD = symMoveUD
        self.sym8Move = sym8Move
        self.moveCubeSym = moveCubeSym
        self.firstMoveSym = firstMoveSym
        self.flipR2S = flip.raw2Sym
        self.flipS2RF = flip.sym2RawFull
        self.twistR2S = twist.raw2Sym
        self.ePermR2S = ePermR2S
        self.perm2CombP = perm2CombP
        self.permInvEdgeSym = permInvEdgeSym
        self.mPermInv = mPermInv
        self.udSliceMove = udSliceMove
        self.twistMove = twistMove
        self.flipMove = flipMove
        self.udSliceConj = udSliceConj
        self.cPermMove = cPermMove
        self.ePermMove = ePermMove
        self.mPermMove = mPermMove
        self.mPermConj = mPermConj
        self.cCombPConj = cCombPConj
    }

    // MARK: Sym coordinates of a cube

    func flipSym(_ c: CubieCube) -> Int { flipR2S[c.flip] }
    func twistSym(_ c: CubieCube) -> Int { twistR2S[c.twist] }
    func cPermSym(_ c: CubieCube) -> Int { eSym2CSym(ePermR2S[c.cperm]) }
    func ePermSym(_ c: CubieCube) -> Int { ePermR2S[c.eperm] }

    func getPermSymInv(_ idx: Int, _ sym: Int, isCorner: Bool) -> Int {
        var idxi = permInvEdgeSym[idx]
        if isCorner {
            idxi = eSym2CSym(idxi)
        }
        return (idxi & 0xfff0) | symMult[(idxi & 0xf) * 16 + sym]
    }

    func getSkipMoves(_ ssym: Int) -> Int {
        var ssym = ssym
        var ret = 0
        var i = 1
        while true {
            ssym >>= 1
            if ssym == 0 {
                break
            }
            if ssym & 1 == 1 {
                ret |= firstMoveSym[i]
            }
            i += 1
        }
        return ret
    }

    // MARK: Table construction

    private enum SymCoord {
        case flip, twist, perm
    }

    private struct SymCoordTables {
        var sym2Raw: [Int]
        var raw2Sym: [Int]
        var symState: [Int]
        /// Flip only: raw flip for each (sym class, symmetry) pair, [336 * 8].
        var sym2RawFull: [Int]
    }

    private struct FlipTables {
        let flipR2S: [Int]
        let flipS2RF: [Int]
        let flipMove: [Int]
        let sym8Move: [Int]
    }

    private static func initSym2Raw(nRaw: Int, nSym: Int, coord: SymCoord, sym: Symmetries) -> SymCoordTables {
        var t = SymCoordTables(
            sym2Raw: [Int](repeating: 0, count: nSym),
            raw2Sym: [Int](repeating: 0, count: nRaw),
            symState: [Int](repeating: 0, count: nSym),
            sym2RawFull: coord == .flip ? [Int](repeating: 0, count: nSym * 8) : []
        )
        var c = CubieCube()
        var d = CubieCube()
        var count = 0
        let symInc = coord == .perm ? 1 : 2
        let isEdge = coord != .twist

        for i in 0..<nRaw {
            if t.raw2Sym[i] != 0 {
                continue
            }
            switch coord {
            case .flip: c.setFlip(i)
            case .twist: c.setTwist(i)
            case .perm: c.setEPerm(i)
            }
            for s in stride(from: 0, to: 16, by: symInc) {
                if isEdge {
                    sym.edgeConjugate(c, s, &d)
                } else {
                    sym.cornConjugate(c, s, &d)
                }
                let idx: Int
                switch coord {
                case .flip: idx = d.flip
                case .twist: idx = d.twist
                case .perm: idx = d.eperm
                }
                if coord == .flip {
                    t.sym2RawFull[(count << 3) | (s >> 1)] = idx
                }
                if idx == i {
                    t.symState[count] |= 1 << (s / symInc)
                }
                t.raw2Sym[idx] = ((count << 4) | s) / symInc
            }
            t.sym2Raw[count] = i
            count += 1
        }
        precondition(count == nSym)
        return t
    }

    /// Breadth-first fill of a pruning table indexed by (sym coordinate, raw coordinate).
    ///
    /// `flag` layout: | MIN_DEPTH 4 | MAX_DEPTH 4 | INV_DEPTH 4 | pad 2 | P2 1 | E2C 1 | SYM_SHIFT 4 |.
    /// When `raw` is nil the raw coordinate is edge flip (twist-flip table), using `flipTables`.
    private static func initRawSymPrun(
        raw: (move: [Int], conj: [Int], conjStride: Int)?,
        flipTables: FlipTables? = nil,
        symMove: [Int],
        symState: [Int],
        flag: Int
    ) -> [UInt32] {
        let symShift = flag & 0xf
        let e2cMagic = (flag >> 4) & 1 == 1 ? symE2CMagic : 0
        let isPhase2 = (flag >> 5) & 1 == 1
        let invDepth = (flag >> 8) & 0xf
        let maxDepth = (flag >> 12) & 0xf

        let symMask = (1 << symShift) - 1
        let nMoves = isPhase2 ? 10 : 18
        let nRaw = raw.map { $0.move.count / nMoves } ?? nFlip
        let nSize = nRaw * (symMove.count / nMoves)
        let nextAxisMagic = nMoves == 10 ? 0x42 : 0x92492

        var table = [UInt32](repeating: 0x1111_1111, count: nSize / 8 + 1)
        setPruning(&table, 0, 0 ^ 1)
        var depth = 0

        while depth < maxDepth {
            let mask = UInt32((depth + 1) * 0x1111_1111) ^ 0xffff_ffff
            for i in 0..<table.count {
                var val = table[i] ^ mask
                val &= val >> 1
                table[i] &+= val & (val >> 2) & 0x1111_1111
            }

            let inv = depth > invDepth
            let select = inv ? depth + 2 : depth
            let selArrMask = UInt32(select * 0x1111_1111)
            let check = inv ? depth : depth + 2
            depth += 1
            let xorVal = depth ^ (depth + 1)

            var i = 0
            var val: UInt32 = 0
            while i < nSize {
                if i & 7 == 0 {
                    val = table[i >> 3]
                    let x = val ^ selArrMask
                    if (x &- 0x1111_1111) & ~x & 0x8888_8888 == 0 {
                        i += 8
                        continue
                    }
                }
                if Int(val & 0xf) != select {
                    i += 1
                    val >>= 4
                    continue
                }
                let rawIdx = i % nRaw
                let symIdx = i / nRaw
                var flip = 0
                var fsym = 0
                if let f = flipTables {
                    flip = f.flipR2S[rawIdx]
                    fsym = flip & 7
                    flip >>= 3
                }

                var m = 0
                while m < nMoves {
                    var symx = symMove[symIdx * nMoves + m]
                    let rawx: Int
                    if let raw {
                        rawx = raw.conj[raw.move[rawIdx * nMoves + m] * raw.conjStride + (symx & symMask)]
                    } else {
                        let f = flipTables!
                        rawx = f.flipS2RF[f.flipMove[flip * 18 + f.sym8Move[(m << 3) | fsym]] ^ fsym ^ (symx & symMask)]
                    }
                    symx >>= symShift
                    let idx = symx * nRaw + rawx
                    let prun = getPruning(table, idx)
                    if prun != check {
                        if prun < depth - 1 {
                            m += (nextAxisMagic >> m) & 3
                        }
                        m += 1
                        continue
                    }
                    if inv {
                        setPruning(&table, i, xorVal)
                        break
                    }
                    setPruning(&table, idx, xorVal)
                    var j = 1
                    var state = symState[symx]
                    while true {
                        state >>= 1
                        if state == 0 {
                            break
                        }
                        if state & 1 == 1 {
                            var idxx = symx * nRaw
                            if let raw {
                                idxx += raw.conj[rawx * raw.conjStride + (j ^ ((e2cMagic >> (j << 1)) & 3))]
                            } else {
                                let f = flipTables!
                                idxx += f.flipS2RF[f.flipR2S[rawx] ^ j]
                            }
                            if getPruning(table, idxx) == check {
                                setPruning(&table, idxx, xorVal)
                            }
                        }
                        j += 1
                    }
                    m += 1
                }
                i += 1
                val >>= 4
            }
        }
        return table
    }
}
